### ISSUE TITLE
Compatibility with other mods

### ISSUE THREAD

**Issue by seriousfreezing** [LordEnder-Kitty/SimpleCloseButton#1]
Will this mod be compatible with other interface mods? Like: Tech Reborn, AE2, and others?

**Comment by LordEnder-Kitty** [comment]
I've been wanting to make it more compatible with other mods but I can't really figure out how to do it. My first idea was to make it a thing in the config where you can just add an entry for each screen, but I can't figure out how to do that.

My idea was maybe you could make an entry which has the name of the class for the screen, the button coordinates, if there's a recipe book and if so, the coordinates for when it's opened, but I don't really know how to get everything working because of all the things necessary to add a button to a screen.

**Comment by LordEnder-Kitty** [comment]
I figured it out! New version coming in a day or two!
